/* Generated By:JavaCC: Do not edit this line. FormulaParserConstants.java */
package edu.tum.cs.logic.parser;

public @SuppressWarnings("all") interface FormulaParserConstants {

  int EOF = 0;
  int NOT = 5;
  int OR = 6;
  int AND = 7;
  int IMPLIES = 8;
  int IFF = 9;
  int EXIST = 10;
  int OPENRB = 11;
  int CLOSERB = 12;
  int LISTSEP = 13;
  int LCCHAR = 14;
  int UCCHAR = 15;
  int DIGIT = 16;
  int IDENTCHAR = 17;
  int NUMBER = 18;
  int UCIDENT = 19;
  int LCIDENT = 20;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"!\"",
    "\"v\"",
    "\"^\"",
    "\"=>\"",
    "\"<=>\"",
    "<EXIST>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "<LCCHAR>",
    "<UCCHAR>",
    "<DIGIT>",
    "<IDENTCHAR>",
    "<NUMBER>",
    "<UCIDENT>",
    "<LCIDENT>",
  };

}
