/* Generated By:JavaCC: Do not edit this line. FormulaParserConstants.java */
package probcog.logic.parser;

public @SuppressWarnings("all") interface FormulaParserConstants {

  int EOF = 0;
  int NOT = 5;
  int OR = 6;
  int AND = 7;
  int IMPLIES = 8;
  int EQUALS = 9;
  int IFF = 10;
  int EXIST = 11;
  int FORALL = 12;
  int OPENRB = 13;
  int CLOSERB = 14;
  int LISTSEP = 15;
  int LCCHAR = 16;
  int UCCHAR = 17;
  int DIGIT = 18;
  int IDENTCHAR = 19;
  int NUMBER = 20;
  int UCIDENT = 21;
  int LCIDENT = 22;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"!\"",
    "\"v\"",
    "\"^\"",
    "\"=>\"",
    "\"=\"",
    "\"<=>\"",
    "<EXIST>",
    "\"FORALL\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "<LCCHAR>",
    "<UCCHAR>",
    "<DIGIT>",
    "<IDENTCHAR>",
    "<NUMBER>",
    "<UCIDENT>",
    "<LCIDENT>",
  };

}
